name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup - gcloud / gsutil
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.GCS_SA_KEY }}
          project_id: virtualairforce
      - name: Deploy
        run: |-
          gsutil -m rsync -R output gs://mod-repo


# name: Deploy To Storage
# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

#   workflow_dispatch:

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
    # - name: Setup - gcloud / gsutil
    #   uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
    #   with:
    #     service_account_key: ${{ secrets.GCS_SA_KEY }}
    #     project_id: virtualairforce
    #     export_default_credentials: true
    # - name: Deploy
    #   run: |-
    #     gsutil -m rsync -R output gs://mod-repo
